const FORM_STEPS = {
  CATEGORIES: 1,
  SUBCATEGORIES: 2,
  SERVICES: 3,
  EMPLOYEES: 4,
  CALENDAR: 5,
  EMPLOYEES_FOR_CURRENT_SLOT: 6,
  CUSTOMER_FORM: 7,
  FINISH: 8,
};

export default FORM_STEPS;